import { CheckIcon,  ArrowLeftIcon, ArrowRightIcon, ArrowUpIcon, ArrowDownIcon,
     PlusIcon, MinusIcon, TrashIcon, PencilIcon, InfoIcon,
      LockIcon, LogOutIcon, UserIcon, SettingsIcon, HelpCircleIcon, 
      BellIcon, CalendarIcon, ClockIcon, DownloadIcon, UploadIcon, SearchIcon,
       FilterIcon, SortIcon, EyeIcon, EyeOffIcon, MenuIcon, XIcon, 
       LoadingIcon, WarningIcon, CancelIcon, EditIcon, DeleteIcon, AlertIcon } from "lucide-react";
            export const icons = {
    check: CheckIcon,
    x: XIcon,
    arrowLeft: ArrowLeftIcon,
    arrowRight: ArrowRightIcon,
    arrowUp: ArrowUpIcon,
    arrowDown: ArrowDownIcon,
    plus: PlusIcon,
    minus: MinusIcon,
    trash: TrashIcon,
    pencil: PencilIcon,
    info: InfoIcon,
    lock: LockIcon,
    logout: LogOutIcon,
    user: UserIcon,
    settings: SettingsIcon,
    helpCircle: HelpCircleIcon,
    bell: BellIcon,
    calendar: CalendarIcon,
    clock: ClockIcon,
    download: DownloadIcon,
    upload: UploadIcon,
    search: SearchIcon,
    filter: FilterIcon,
    sort: SortIcon,
    eye: EyeIcon,
    eyeOff: EyeOffIcon,
    menu: MenuIcon,
    loading: LoadingIcon,
    warning: WarningIcon,
    cancel: CancelIcon,
    edit: EditIcon,
    delete: DeleteIcon,
    alert: AlertIcon,

}